name: get_lia
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - rioxarray
  - xarray
  - geopandas
  - planetary-computer
  - pystac-client
  - pystac
  - stackstac
  - adlfs
  - pip:
    - sarsen==0.9.2